[target.aarch64-apple-darwin]
rustflags = "-lc++ -l framework=Accelerate"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = [ "-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc" ]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
